/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as counterSol from './Counter.sol/index.js';
export type { counterSol };
import type * as basics from './basics/index.js';
export type { basics };
export * as factories from './factories/index.js';
export type { Variables } from './basics/Variables.sol/Variables.js';
export { Variables__factory } from './factories/basics/Variables.sol/Variables__factory.js';
export type { Counter } from './Counter.sol/Counter.js';
export { Counter__factory } from './factories/Counter.sol/Counter__factory.js';